[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvasptools"
version = "0.0.9"
dependencies = [
    "py4vasp",
    "pymatgen",     
    "matplotlib >= 3.10.1", 
    "numpy >= 1.26.4",     
    "pandas >= 2.2.3", 
    "diptest >= 0.9.0", 
    "vasppy >= 0.7.1.0", 
    ]
requires-python = ">=3.10.14"
authors = [
  {name = "Agnes Katai", email = "agneskatai6@gmail.com"},
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyvasptools*"]